using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectEuler
{
    /// <summary>
    /// Problem 2: Even Fibonacci numbers
    /// https://projecteuler.net/problem=2
    /// 
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Prb2_EvenFibonacciNumbers
    {
        private readonly IList<int> _fibonacciList = new List<int> {1,2} ; 
        public int Sum_Of_Even_Valued_Terms(int exclusiveUpper)
        {
            return Find_Fibonacci_Sequence(exclusiveUpper).Where(x => x%2 == 0).Sum();           
        }

        public IEnumerable<int> Find_Fibonacci_Sequence(int inclusiveUpper)
        {
            if (inclusiveUpper <= 2)
                return _fibonacciList.Take(inclusiveUpper);

            while (_fibonacciList.Last() < inclusiveUpper)
            {
                var nextFibonacci = _fibonacciList[_fibonacciList.Count - 2] + _fibonacciList.Last();
                _fibonacciList.Add(nextFibonacci);
            }
            return _fibonacciList.Where(x => x <= inclusiveUpper);
        }
    }
}